
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
    url: jdbc:postgresql://localhost:5432/hospitaldb
    platform: postgres

  liquibase:
      change-log: classpath:/db/changelog/db.changelog-master/db.changelog-master.yml
  jpa:
    show-sql: true





